apiVersion: v1
kind: Service
metadata:
  name: username
spec:
  type: NodePort
  selector:
    app: username
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: username-deployment
  labels:
    app: username
spec:
  replicas: 2
  selector:
    matchLabels:
      app: username
  template:
    metadata:
      labels:
        app: username
    spec:
      containers:
      - name: nginx
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
