apiVersion: v1
kind: Service
metadata:
  name: jai
spec:
  type: NodePort
  selector:
    app: jai
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jai-deployment
  labels:
    app: jai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jai
  template:
    metadata:
      labels:
        app: jai
    spec:
      containers:
      - name: nginx
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
